# .github/workflows/trigger-another-repo.yml
name: Trigger Another Repo

on:
  workflow_dispatch: 
    
jobs:
  trigger:
    runs-on: windows-latest
    steps:
      - name: Trigger workflow in target repo using PowerShell
        shell: pwsh
        run: |
          $headers = @{
            "Accept" = "application/vnd.github+json"
            "Authorization" = "Bearer ${{ secrets.PAT_GH_LEARN }}"
          }

          # Ref needs to be exact
          $body = @{
            ref = "Main"
          } | ConvertTo-Json

          #Target Repo URL
          $Owner         = "astowell8"  # Owner or Org
          $Repo          = "GH-Actions-Learn-DiffRepo"
          $workflow_yaml = "Diff-Repo.yaml"
          #$workflow_yaml = "Say-Hello.yml"

          $uri = "https://api.github.com/repos/$Owner/$Repo/actions/workflows/$workflow_yaml/dispatches"

          Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body
